db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://ep-raspy-sea-aixi8yaf-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
db.username=neondb_owner
db.password=npg_7APEQ0rOJKHZ